apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: lisi-4
  labels:
    app: deploy-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-nginx
  template:
    metadata:
      labels:
        app: deploy-nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/library/nginx:stable
          ports:
            - containerPort: 80
