apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  namespace: lisi-4
  labels:
    app: pod-nginx
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:stable
      ports:
        - containerPort: 80
      resources:
            limits:
              cpu: 10m
